### ISSUE TITLE
Bug when fitting any model with more than one element in class

### ISSUE THREAD

**Issue by matherealize** [biometrician/abe#54]
In the latest version of the abe package (5.1.1) there is a bug when fitting any model that has multiple elements in its class attribute, e.g. a `glm`. 

# Steps to reproduce 

```
m = glm(Species == "virginica" ~ Sepal.Length + Sepal.Width, data = iris, x = TRUE)
abe(m, data = iris)
``` 
 Results in 
```
Error in if (class(bt0) == "try-error") bt else bt0 : 
  the condition has length > 1
```

# Cause

Before returning `abe()` checks the model class for a try-error: https://github.com/biometrician/abe/blob/d3f464504e6af06f089f38435417ba0bf6702cb2/R/abe.R#L273C1-L274C41

This doesn't work since `class(m)` has two entries `"glm" "lm"`.

# Fix

The idiomatic way to check for a try-error is probably to use `inherits(m, "try-error")`, i.e. to change the code to

```
if (inherits(bt0, "try-error")) bt else bt0
```

**Comment by thullmann** [comment]
Fixed with commit [6e6a3ec](https://github.com/biometrician/abe/commit/6e6a3ec97db62319e216f865d9821f520428b473)
